### ISSUE TITLE
Message Icons

### ISSUE THREAD

**Issue by NetSpeedz** [DM164/Dark-by-DM#11]
The icons that are below the GMail search bar are so dark, they are difficult to see. Is there a way to 'colorize' these icons so they are easier to see? 

Appreciate your efforts in this much needed style for GMail :-)

**Comment by DM164** [comment]
![image](https://user-images.githubusercontent.com/41427432/90504756-d7f54f00-e151-11ea-890c-d6de1fb4071d.png)
You mean these? They should be styled like in the screenshot, you just need to go to themes in Gmail and select the default theme so that it doesn't conflict with the dark mode.
Let me know if it solved the problem

**Comment by NetSpeedz** [comment]
Changing the GMail default theme fixed the problem.

I do recall reading in the Userstyle post to set the GMail theme to
default. Apologies for the ticket.

Appreciate your help.


J.A. Clark

------------

**Comment by DM164** [comment]
No problem I'm glad you could solve the problem.
Have a nice day and stay safe!
